sudo: false
language: php

php:
  - 5.4

before_script:
  # Set the GitHub OAuth token to make use of the 6000 per hour rate limit
  - "mkdir -p ~/.composer"
  - cp .travis.composer.config.json ~/.composer/config.json

script:
  - composer install --dev --no-interaction
  - phpunit

after_script:
  - php vendor/bin/coveralls -v
